'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'
import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useLocalStorage } from 'usehooks-ts'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Kedai Bu Titin',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();
  const [check, setCheck] = useState(false);
  const [accessToken, _] = useLocalStorage('accessToken', '');
  const [refreshToken, __] = useLocalStorage('refreshToken', '');
  const pathname = usePathname()
  

  useEffect(() => {
    console.log(pathname);
    if (pathname === '/page/dashboard/FormLogin' || pathname === '/page/pemesanan' || pathname === '/page/landingPage' || pathname === '/page/pemesanan/DetailPemesanan' || pathname === '/page/landingPage' || pathname === '/page/landingPage/loginPegawai' || pathname === '/page/landingPage/home' || pathname === '/page/landingPage/buatPassword' || pathname === '/page/landingPage/kodeOTP' || pathname === '/page/landingPage/lupaPassword') {
      setCheck(true);
      return
    }
    if (!accessToken) {
      setCheck(false);
      if(pathname === '/page/landingPage/dashboardRekrut'){
        router.push('/page/landingPage/loginPegawai');
      }else{
        router.push('/page/dashboard/FormLogin'); 
      }
    } else {
      // MAU TAMBAH KONDISI LAGI
      setCheck(true);
    }
    
    return () => {
      
    }
  }, [pathname, accessToken,refreshToken]);
  return (
    <html lang="en">
      <body className={montserrat.className}>{check ? children : <div className='h-screen flex justify-center items-center'>Loading...</div>}</body>
    </html>
  )
}
